import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Hotel App - Ujikom",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased  dark:text-gray-100 dark:bg-blue-gray-900`}
          >
      <Providers>
            {children}

      </Providers>
          
          </body>

        </html>
  );
}
